[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt",
    "cd frontend && npm install && npm run build"
]

[start]
cmd = "python3 backend/app.py"