[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm install && npm run build"
]

[start]
cmd = "python backend/app.py"